version: "3.9"

services:
  backend:
    build: ./backend
    container_name: task-tracker-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules  # prevent overwriting installed node_modules
    command: ["npm", "start"]

  frontend:
    build: ./frontend
    container_name: task-tracker-frontend
    restart: always
    ports:
      - "5173:80"
